#!/bin/sh

# The CVS contains some files that technically aren't needed to build from the
# bare bottom of the source.  To remove those files, run:
#     make really-clean
# To recreate those files, two things need to be done:
#     ./bootstrap
#     cd bitmaps; make

rm -f config.cache Makefile src/Makefile configure 
./bootstrap
./configure --enable-alsa=yes --enable-sequencer2=yes
cd bitmaps; make; cd ..
make
