/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MIDI_P_H_RPCGEN
#define _MIDI_P_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int midi_buf_len;
	char *midi_buf_val;
} midi_buf;

#define MIDINET_PROG 0x40000001
#define MIDINET_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define mpu_write_ack 1
extern  int * mpu_write_ack_1(midi_buf *, CLIENT *);
extern  int * mpu_write_ack_1_svc(midi_buf *, struct svc_req *);
#define mpu_write_noack 2
extern  void * mpu_write_noack_1(midi_buf *, CLIENT *);
extern  void * mpu_write_noack_1_svc(midi_buf *, struct svc_req *);
extern int midinet_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mpu_write_ack 1
extern  int * mpu_write_ack_1();
extern  int * mpu_write_ack_1_svc();
#define mpu_write_noack 2
extern  void * mpu_write_noack_1();
extern  void * mpu_write_noack_1_svc();
extern int midinet_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_midi_buf (XDR *, midi_buf*);

#else /* K&R C */
extern bool_t xdr_midi_buf ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MIDI_P_H_RPCGEN */
